<template lang="">
  <div class="container h-96">
    <Avatar />
    <div class="max-w-2xl m-auto m-0">
      <a-collapse v-model:activeKey="activeKey">
        <a-collapse-panel key="1" header="Menu" :disabled="false" class="">
          <div v-for="item in data">name: {{ item.name }}</div>
          <div v-for="item in data">
            <div v-if="item.children">name: {{ item.name }}</div>
          </div>
        </a-collapse-panel>
      </a-collapse>
    </div>
  </div>
</template>
<script>
import { mapGetters, mapMutations } from "vuex";
import Avatar from "@/components/Avatar";
import { refreshToken } from "@/api/AuthenConnector.js";

export default {
  // middleware: "auth",
  components: { Avatar },
  data() {
    return {
      data: [
        {
          key: 3,
          parentId: 0,
          name: "Văn phòng",
          office: 0,
          enterprise: null,
          laborProductivity: 0,
          ratio: 0,
          totalLaborProductivity: 30,
          numberLeave: 0,
          partTimeEmp: null,
          totalRatioOfOfficeAndDonvile: 100,
          rice: {
            riceCus: 0,
            riceVip: 0,
            riceEmp: 0,
          },
          children: [
            {
              key: 123,
              parentId: 3,
              name: "Tổ Vệ sinh VP",
              office: 0,
              enterprise: null,
              laborProductivity: 0,
              ratio: null,
              totalLaborProductivity: null,
              numberLeave: 0,
              partTimeEmp: null,
              totalRatioOfOfficeAndDonvile: null,
              rice: {
                riceCus: 0,
                riceVip: 0,
                riceEmp: 0,
              },
              children: null,
            },
          ],
        },
        {
          key: 2,
          parentId: 0,
          name: "Đơn vị lẻ",
          office: null,
          enterprise: null,
          laborProductivity: 30,
          ratio: 100,
          totalLaborProductivity: null,
          numberLeave: 1,
          partTimeEmp: null,
          totalRatioOfOfficeAndDonvile: 100,
          rice: {
            riceCus: 0,
            riceVip: 0,
            riceEmp: 0,
          },
          children: [
            {
              key: 94,
              parentId: 2,
              name: "Xí nghiệp 1",
              office: null,
              enterprise: 31,
              laborProductivity: 30,
              ratio: 100,
              totalLaborProductivity: null,
              numberLeave: 1,
              partTimeEmp: null,
              totalRatioOfOfficeAndDonvile: null,
              rice: {
                riceCus: 0,
                riceVip: 0,
                riceEmp: 0,
              },
              children: [
                {
                  key: 127,
                  parentId: 94,
                  name: "Vệ Sinh 1",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 131,
                  parentId: 94,
                  name: "Tổ Hoàn thiện 1",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 132,
                  parentId: 94,
                  name: "Rải Chuyền 1",
                  office: null,
                  enterprise: 31,
                  laborProductivity: 30,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 1,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
              ],
            },
            {
              key: 93,
              parentId: 2,
              name: "Xí nghiệp 2",
              office: null,
              enterprise: 0,
              laborProductivity: 0,
              ratio: 0,
              totalLaborProductivity: null,
              numberLeave: 0,
              partTimeEmp: null,
              totalRatioOfOfficeAndDonvile: null,
              rice: {
                riceCus: 0,
                riceVip: 0,
                riceEmp: 0,
              },
              children: [
                {
                  key: 134,
                  parentId: 93,
                  name: "Vệ sinh 2",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
              ],
            },
          ],
        },
        {
          key: 1,
          parentId: 0,
          name: "Tổ May",
          office: null,
          enterprise: 0,
          laborProductivity: 0,
          ratio: 0,
          totalLaborProductivity: null,
          numberLeave: 0,
          partTimeEmp: null,
          totalRatioOfOfficeAndDonvile: null,
          rice: {
            riceCus: 0,
            riceVip: 0,
            riceEmp: 0,
          },
          children: [
            {
              key: 89,
              parentId: 1,
              name: "Xí nghiệp 1",
              office: null,
              enterprise: 0,
              laborProductivity: 0,
              ratio: 0,
              totalLaborProductivity: null,
              numberLeave: 0,
              partTimeEmp: null,
              totalRatioOfOfficeAndDonvile: null,
              rice: {
                riceCus: 0,
                riceVip: 0,
                riceEmp: 0,
              },
              children: [
                {
                  key: 143,
                  parentId: 89,
                  name: "Tổ may 03",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 144,
                  parentId: 89,
                  name: "Tổ may 04",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 145,
                  parentId: 89,
                  name: "Tổ may 05",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 147,
                  parentId: 89,
                  name: "Tổ may 07",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 148,
                  parentId: 89,
                  name: "Tổ may 08",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 149,
                  parentId: 89,
                  name: "Tổ may 09",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 150,
                  parentId: 89,
                  name: "Tổ may 10",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 151,
                  parentId: 89,
                  name: "Tổ may 11",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 153,
                  parentId: 89,
                  name: "Tổ may 13",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 154,
                  parentId: 89,
                  name: "Tổ may 14",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 156,
                  parentId: 89,
                  name: "Tổ may 16",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 159,
                  parentId: 89,
                  name: "Tổ may 19",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
              ],
            },
            {
              key: 88,
              parentId: 1,
              name: "Xí nghiệp 2",
              office: null,
              enterprise: 0,
              laborProductivity: 0,
              ratio: 0,
              totalLaborProductivity: null,
              numberLeave: 0,
              partTimeEmp: null,
              totalRatioOfOfficeAndDonvile: null,
              rice: {
                riceCus: 0,
                riceVip: 0,
                riceEmp: 0,
              },
              children: [
                {
                  key: 161,
                  parentId: 88,
                  name: "Tổ may 21",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 166,
                  parentId: 88,
                  name: "Tổ may 26",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 168,
                  parentId: 88,
                  name: "Tổ may 28",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 170,
                  parentId: 88,
                  name: "Tổ may 30",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 173,
                  parentId: 88,
                  name: "Tổ may 33",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 176,
                  parentId: 88,
                  name: "Tổ may 36",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
                {
                  key: 177,
                  parentId: 88,
                  name: "Tổ may 37",
                  office: null,
                  enterprise: 0,
                  laborProductivity: 0,
                  ratio: null,
                  totalLaborProductivity: null,
                  numberLeave: 0,
                  partTimeEmp: null,
                  totalRatioOfOfficeAndDonvile: null,
                  rice: {
                    riceCus: 0,
                    riceVip: 0,
                    riceEmp: 0,
                  },
                  children: null,
                },
              ],
            },
          ],
        },
        {
          key: 0,
          parentId: 0,
          name: "Học sinh chưa báo năng suất",
          office: null,
          enterprise: 0,
          laborProductivity: 0,
          ratio: 0,
          totalLaborProductivity: null,
          numberLeave: 0,
          partTimeEmp: null,
          totalRatioOfOfficeAndDonvile: null,
          rice: {
            riceCus: 0,
            riceVip: 0,
            riceEmp: 0,
          },
          children: null,
        },
        {
          key: 0,
          parentId: 0,
          name: "Thời vụ tổ may",
          office: null,
          enterprise: 0,
          laborProductivity: 0,
          ratio: 0,
          totalLaborProductivity: null,
          numberLeave: 0,
          partTimeEmp: null,
          totalRatioOfOfficeAndDonvile: null,
          rice: {
            riceCus: 0,
            riceVip: 0,
            riceEmp: 0,
          },
          children: null,
        },
        {
          key: 0,
          parentId: 0,
          name: "Thời vụ đơn vị lẻ ",
          office: null,
          enterprise: 0,
          laborProductivity: 0,
          ratio: 0,
          totalLaborProductivity: null,
          numberLeave: 0,
          partTimeEmp: null,
          totalRatioOfOfficeAndDonvile: null,
          rice: {
            riceCus: 0,
            riceVip: 0,
            riceEmp: 0,
          },
          children: null,
        },
      ],
    };
  },
};
</script>
<style scoped>
.menuBtn {
  background-color: #045396;
  color: #ffff;
}
</style>
